Lesson 5
Kouler/fefu_backend_2_3 pull request #7
Opened 2021-12-29 16:46 UTC by Kouler

git push --set-upstream origin lesson-5. Check it :)

2022-01-13 13:36 UTC, chrn-feip commented
Наведите порядок в коммитах. Ребейз надо делать в вашем форке, имея свежий master. Т.е. всякий раз, когда ваш PR вливают: идете в локальный master, делаете git pull, переключаетесь на форк, делаете git rebase master. Решаете конфликты, если они есть, делаете git push -f origin <fork name>. В каждом PR на начало его проверки должен быть один единственный коммит - с кодом задания.

2022-01-13 13:55 UTC, chrn-feip requested changes

2022-01-13 13:55 UTC, chrn-feip commented on resources/views/newsList.blade.php
> +    @foreach($news->links()->elements[0] as $page)
Это не нужно делать вручную. https://laravel.su/docs/8.x/pagination#displaying-pagination-results

2022-01-13 13:55 UTC, chrn-feip commented on resources/views/newsList.blade.php
> +                    <p>{{ $item->description }}</p></div>
Краткое описание может быть null, в таком случае \<p\> лучше вообще не рендерить.

2022-01-13 13:55 UTC, chrn-feip commented on routes/web.php
> +Route::get('/appeal', AppealController::class)->name('appeal');
Если у вас используется invokable контроллер с единственным методом, который отрабатывает и на POST, и на GET, то лучше маршрут записывать одной строкой с match.

2022-01-13 13:55 UTC, chrn-feip commented on app/Http/Controllers/AppealController.php
> +                'email' => 'required_without:phone|nullable|regex:/^.+@.+$/i|max:100',
1. Регулярка для почты некорректна. Используйте хотя бы встроенное правило валидации вместо этого. https://laravel.su/docs/8.x/validation#rule-email
2. Строго говоря, валидацией данных формы мы занимаемся в следующем ДЗ.

2022-01-13 13:57 UTC, chrn-feip commented
Делайте, пожалуйста, ребейз для всех PR, как я описала выше. Имеющаяся структура коммитов осложняет проверку, в списке изменённых файлов я вижу лишние, как например тут новости. В которых ещё и ошибки есть.

2022-01-13 14:02 UTC, Kouler commented on resources/views/newsList.blade.php
> +    @foreach($news->links()->elements[0] as $page)
я когда писал только users->links() и всё, у меня отображались и страницы в виде цифр, и ужасно огромные две стрелки влево, вправо, ещё парочку каких-то кнопок управления. Я поэтому и решил прописать, виделить исключительно только номера страниц и всё

2022-01-13 14:04 UTC, Kouler commented on resources/views/newsList.blade.php
> +    @foreach($news->links()->elements[0] as $page)
мне просто оставить {{$users->links()}} и всё или мб такое тоже сойдёт? это просто вроде не ошибка, а наоборот, сверх нормы

2022-01-13 14:08 UTC, Kouler commented on routes/web.php
> +Route::get('/appeal', AppealController::class)->name('appeal');
хорошо, сделаю

2022-01-13 14:08 UTC, Kouler commented on app/Http/Controllers/AppealController.php
> +            $success = '';
удалил его уже в след уроке, здесь тоже удалю

2022-01-13 14:09 UTC, chrn-feip commented on resources/views/newsList.blade.php
> +    @foreach($news->links()->elements[0] as $page)
оставьте

2022-01-14 16:02 UTC, Kouler commented
Исправил + ребейз

2022-01-16 13:58 UTC, merged