Lesson 6: Validate and sanitize appeal form input
Kouler/fefu_backend_2_3 pull request #8
Opened 2022-01-13 08:48 UTC by Kouler

Проверьте

2022-01-13 14:26 UTC, chrn-feip requested changes

2022-01-13 14:26 UTC, chrn-feip commented on resources/views/appeal.blade.php
> +{{--                <div id="gender-radios">--}}
Никаких закомментированных кусков! Если код не нужен, он не должен в репозиторий попасть вообще.

2022-01-13 14:26 UTC, chrn-feip commented on resources/views/appeal.blade.php
> +                <input value="{{ old('phone') }}" placeholder="+7(000) 000-00-00" type="tel" pattern="(\+7|7|8){1}\(\d{3}\) \d{3}-\d{2}-\d{2}" class="my-input form-control" name="phone" id="phone">
Никаких масок в шаблоне. Наша задача - написать валидацию на сервере, не надо фронтендом облегчать себе жизнь.

2022-01-13 14:26 UTC, chrn-feip commented on resources/views/appeal.blade.php
> +                <input value="{{ old('surname') }}" placeholder="Введите фамилию" type="text" class="my-input form-control" name="surname" id="surname">
old нужно использовать только в том случае, если были ошибки заполнения формы. Иначе после успешной отправки, форма всё равно будет заполнена после редиректа на GET маршрут. А должна быть пустой.

2022-01-13 14:26 UTC, chrn-feip commented on database/seeders/DatabaseSeeder.php
> +        \App\Models\News::truncate();
Всё, что касается новостей, после всех ребейзов, должно исчезнуть из этого PR. Никаких посторонних изменений в коде ДЗ, пожалуйста.

2022-01-13 14:26 UTC, chrn-feip commented on app/Http/Requests/AppealPostRequest.php
> +            'email' => 'required_without:phone|nullable|regex:/^.+@.+$/|max:100|string',
некорректная регулярка для почты

2022-01-13 14:26 UTC, chrn-feip commented on app/Http/Controllers/AppealController.php
> +            return redirect()->back()->with('message', 'Сообщение успешно отправлено и зарегистрировано');
То же самое про редирект, что и в предыдущем PR.

2022-01-13 14:29 UTC, Kouler commented on resources/views/appeal.blade.php
> +                <input value="{{ old('surname') }}" placeholder="Введите фамилию" type="text" class="my-input form-control" name="surname" id="surname">
аа, ну вот, а я как раз поэтому и делал редирект back(), чтобы пустой была😂

2022-01-13 14:44 UTC, chrn-feip commented on resources/views/appeal.blade.php
> +                <input value="{{ old('surname') }}" placeholder="Введите фамилию" type="text" class="my-input form-control" name="surname" id="surname">
Про back я уже объяснила. Мы можем сделать сразу POST запрос мимо формы через тот же Postman, отправив корректный payload. Тогда back попросту не будет существовать.

2022-01-14 16:18 UTC, Kouler commented on resources/views/appeal.blade.php
> +                <input value="{{ old('surname') }}" placeholder="Введите фамилию" type="text" class="my-input form-control" name="surname" id="surname">
так, а я сделал редирект()->route('appeal') и олды работают, если ошибки есть, и исчезают, если сообщение успешно. При этом не менял, input value="{{ old('surname') }}" так и осталось

2022-01-14 16:29 UTC, Kouler commented
ой, не "Lesson 5", а "Lesson 6" в последнем коммите: "Lesson 5: rebase from lesson-5 and merged". Ошибся. 
Проверьте)

2022-01-16 14:08 UTC, chrn-feip commented
Так. Я не буду это проверять до тех пор, пока вы не сделаете нормальную ветку. 40 коммитов в PR - это отвратительно. Вероятно, вы неправильно делаете ребейз. Есть два пути, выберите то, что вам проще и сделайте ветку с нормальной историей изменений:
1. Идёте в локальную ветку master, делаете git pull. Таким образом, получая всю свежую историю. Идёте в локальную ветку lesson-6 и делаете там git rebase master. В процессе решаете конфликты, коммитите, проверяете, что всё работает, проверяете, что все ваши новые изменения по ДЗ оказались в одном коммите, который находится наверху в истории, см. git log --oneline. После того, как убедились, что всё хорошо, делаете  git push -f origin lesson-6. Так вы в гитхабе получает ветку с 1 целевым коммитом.
2. Идёте в локальную ветку master, делаете git pull. Делаете новую ветку от этого свежего master. Переключаетесь на неё. И в ней делаете git cherry-pick <sha хэш целевого коммита>. Хэш можно найти и скопировать на гитхабе в списке коммитов вашей ветки lesson-6 или скопировать его из лога коммитов в вашей локальной ветке lesson-6 (но тогда нужно будет переключаться туда-сюда). cherry-pick копирует коммит с изменениями из одного места в другое по хэшу. Далее также всё тестируете и в конце делаете git push -f ... PR это редактируете, чтобы from была ваша новая ветка. Старую ветку удаляете из гитхаба и локально.

2022-01-19 07:04 UTC, closed without merging